### ISSUE TITLE
404s on live site

### ISSUE THREAD

**Issue by natdempk** [dcalacci/open-itinerary#8]
Get Recommendations button produces:
![image](https://cloud.githubusercontent.com/assets/1648519/4368079/fb274b48-42e4-11e4-8d2f-ab3e00440a93.png)
Similar thing happens with Route Recommendations

Clicking Find produces:
![image](https://cloud.githubusercontent.com/assets/1648519/4368086/326d5138-42e5-11e4-88d2-c0f9e88ad789.png)

**Comment by dcalacci** [comment]
fixed! this was a problem with deployment.
