### ISSUE TITLE
Changing page URL when Itinerary is created doesn't work on live site

### ISSUE THREAD

**Issue by natdempk** [dcalacci/open-itinerary#9]
Console output:
![image](https://cloud.githubusercontent.com/assets/1648519/4368411/7a7ea178-42ec-11e4-975e-76bdda3bf3f0.png)

Happens after clicking find for the first time

**Comment by zdhickman** [comment]
the port, :5000

**Comment by dcalacci** [comment]
This still happens even after it's pushed to the new site

**Comment by zdhickman** [comment]
the port is hardcoded!!!! just fix it in the code

**Comment by natdempk** [comment]
@dcalacci needs to fix this, as we don't know what port his server is configured to use

**Comment by dcalacci** [comment]
ok! I just need to remove the port
